name = "Cobblemon Starfall Modpack"
author = "Tastic Productions"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0b6280b0f8498024a6f30f337a74162a5d55883c17e8201ec38dbad18254aaa2"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
