name = "Cobblemon Starfall Modpack"
author = "Tastic Productions"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c44779cf818badad650233d1be1cb4429332c468c69871e8cc02675b8d86bc4e"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
