name = "Cobblemon Starfall Modpack"
author = "Tastic Productions"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cecb68cdfd001a0aa31ffa37fee9e2af78ea14df043c2b7684668414e9049ede"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
